version: '3.1'
services:
  stats-server:
    build: stats/stats-server
    image: stats-server
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/stats-db

  stats-db:
    image: postgres:15.3-alpine
    container_name: stats-db
    ports:
      - "6551:5432"
    environment:
      - POSTGRES_DB=stats-db
        - POSTGRES_USER=user
        - POSTGRES_PASSWORD=password123

  ewm-service:
    build: main-service
    image: main-service
    container_name: main-service
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    environment:
      - STATS_SERVER_URL=http://stats-server:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/ewm-db

  ewm-db:
    image: postgres:15.3-alpine
    container_name: ewm-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=ewm-db
        - POSTGRES_USER=user
        - POSTGRES_PASSWORD=password123